version: '3'
services:
  temporal-zookeeper:
    image: zookeeper:3.9.2
    container_name: temporal-zookeeper
    restart: unless-stopped
    ports:
      - 3011:2181

  # Kafka instance
  temporal-kafka:
    image: 'bitnami/kafka:3.3.1'
    container_name: temporal-kafka
    restart: unless-stopped
    ports:
      - 3012:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=temporal-zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://temporal-kafka:9092,INTERNAL://temporal-kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:3012,INTERNAL://temporal-kafka:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - temporal-zookeeper

volumes:
  temporal-postgres-data:
